//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 127.0.0.1.
        /// </summary>
        internal static string ServerIp {
            get {
                return ResourceManager.GetString("ServerIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 10000.
        /// </summary>
        internal static string ServerPort {
            get {
                return ResourceManager.GetString("ServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mgo+DSMBaFt/QHRqVVhkXlpGaVxdX2NLfUN/T2ZQdVp0ZCQ7a15RRnVfQ11mSH5Rd0VjX39Xcg==;Mgo+DSMBPh8sVXJ0S0J+XE9AdFRAQmBWfFN0RnNQdVt5flFCcC0sT3RfQF5jSH5Wd0VhWH9ednZWRA==;ORg4AjUWIQA/Gnt2VVhkQlFacl1JX3xKYVF2R2BJdlR1fV9CZEwgOX1dQl9gSX9Tc0RjW35ecHJWTmE=;ODgyODQ5QDMyMzAyZTM0MmUzMFI0Q2JGNVdiTzBtSG1rc0dscG5kTk94aVFxVU5aaVlkaWc4ZFpNWGl0N0E9;ODgyODUwQDMyMzAyZTM0MmUzMFJqcjNxakJvS2JBaE5LWkFFM3RQNHBYbFJFUGV4K2RVajE4c240Tm9oUDg9;NRAiBiAaIQQuGjN/V0Z+WE9EaFtAVmFWfUx0RWFab1d6cVxMZFhBNQtUQF1hSn5SdkBiWX1fcHRSR2hd;ODgyODUyQDMyMzAyZTM0Mm [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string SyncfusionLicenceKey {
            get {
                return ResourceManager.GetString("SyncfusionLicenceKey", resourceCulture);
            }
        }
    }
}
